version: "3.8"
services:
  nestjs_app:
    build:
      context: .
      dockerfile: dockerfiles/back.dockerfile
    image: nestjs_app
    container_name: nestjs_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/front.dockerfile
    image: frontend
    container_name: frontend
    init: true
    environment:
      NODE_ENV: "stage"
    ports:
      - "8082:8081"
    volumes:
      - public:/app/public

  postgres:
    image: postgres:16.1
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 221414
      POSTGRES_DB: order-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    restart: always
    links:
      - nestjs_app
      - frontend
    depends_on:
      - nestjs_app
      - frontend
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d/
      - public:/app/build:ro

volumes:
  public:
  postgres_data:
